name: GXDE Base System Builder (amd64)
run-name: ${{ github.actor }} Building GXDE Base System (amd64) ğŸš€
on:
  workflow_dispatch:
  push:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Building .squashfs
        run: |
          # è·å–æ‰€éœ€æ•°æ®
          cpu=$(cat /proc/cpuinfo | grep processor | wc -l)
          # é…ç½®ç¯å¢ƒ
          sudo apt update
          sudo apt install squashfs-tools qemu-user-static debootstrap xz-utils git -y
          cd ~
          # éƒ¨ç½² chroot ç¯å¢ƒ
          sudo debootstrap bookworm debian
          wget https://github.com/gfdgd-xi/deep-wine-runner/raw/main/pardus-chroot
          wget https://github.com/GXDE-OS/dde15-for-debian12/raw/main/.github/workflows/config.sh
          sudo cp pardus-chroot /usr/bin
          sudo chmod 777 /usr/bin/pardus-chroot
          sudo pardus-chroot debian
          ### é…ç½®å®¹å™¨
          sudo cp ~/config.sh debian
          sudo chroot debian apt install linux-headers-amd64 linux-image-amd64 -y
          sudo chroot debian bash /config.sh
          ### å–æ¶ˆæŒ‚è½½
          sudo umount debian/dev/pts
          sudo umount debian/dev/shm
          sudo umount debian/dev/
          sudo umount debian/media
          sudo umount debian/run
          sudo umount debian/sys
          sudo umount debian/proc
          sudo umount debian/tmp
          ### ç”Ÿæˆ squashfs æ–‡ä»¶
          cd debian
          sudo mksquashfs . ~/filesystem.squashfs
      - name: upload .squashfs result
        uses: actions/upload-artifact@v1
        with:
          name: filesystem.squashfs
          path: /home/runner/filesystem.squashfs
      
    